version: "3.6"

services:
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
  pgadmin4:
    depends_on:
      - db
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: test
    ports:
      - "1111:80"
    links:
      - "db:db"
  help:
    depends_on:
      - pgadmin4
    image: alpine
    command: echo -e "\n\nBrowse to http://localhost:1111 to access pgadmin.\nHard-reload the page if you get 'The CSRF session token is missing.' errors.\nLogin with 'admin@test.com/test'.\nConnect to server 'db' as 'postgres/root'.\n\n"
