FROM golang:1.14.1-alpine3.11
RUN apk add build-base

WORKDIR /build
COPY . ./

RUN go build -o iovnscli ./cmd/iovnscli
RUN go build -o iovnsd ./cmd/iovnsd

FROM alpine
ENV HOME=/iovns
ENV MONIKER=k8sclient
COPY --from=0 /build/iovnscli /bin/iovnscli
COPY --from=0 /build/iovnsd /bin/iovnsd
WORKDIR /scripts
COPY ./scripts .
RUN chmod +x /scripts/entrypoint.sh
RUN chmod +x /scripts/new_net.sh
WORKDIR /iovns
ENTRYPOINT ["/scripts/entrypoint.sh"]