// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: x/configuration/types/types.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types1 "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	types "github.com/gogo/protobuf/types"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Config is the configuration of the network
type Config struct {
	// Configurer is the configuration owner, the addresses allowed to handle fees
	// and register domains with no superuser
	Configurer github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,1,opt,name=Configurer,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"configurer"`
	// ValidDomainName defines a regexp that determines if a domain name is valid or not
	ValidDomainName string `protobuf:"bytes,2,opt,name=ValidDomainName,proto3" json:"valid_domain_name"`
	// ValidAccountName defines a regexp that determines if an account name is valid or not
	ValidAccountName string `protobuf:"bytes,3,opt,name=ValidAccountName,proto3" json:"valid_account_name"`
	// ValidURI defines a regexp that determines if resource uri is valid or not
	ValidURI string `protobuf:"bytes,4,opt,name=ValidURI,proto3" json:"valid_uri"`
	// ValidResource determines a regexp for a resource content
	ValidResource string `protobuf:"bytes,5,opt,name=ValidResource,proto3" json:"valid_resource"`
	// DomainRenewalPeriod defines the duration of the domain renewal period in seconds
	DomainRenewalPeriod types.Duration `protobuf:"bytes,6,opt,name=DomainRenewalPeriod,proto3" json:"domain_renewal_period"`
	// DomainRenewalCountMax defines maximum number of domain renewals a user can do
	DomainRenewalCountMax uint32 `protobuf:"varint,7,opt,name=DomainRenewalCountMax,proto3" json:"domain_renewal_count_max"`
	// DomainGracePeriod defines the grace period for a domain deletion in seconds
	DomainGracePeriod types.Duration `protobuf:"bytes,8,opt,name=DomainGracePeriod,proto3" json:"domain_grace_period"`
	// AccountRenewalPeriod defines the duration of the account renewal period in seconds
	AccountRenewalPeriod types.Duration `protobuf:"bytes,9,opt,name=AccountRenewalPeriod,proto3" json:"account_renewal_period"`
	// AccountRenewalCountMax defines maximum number of account renewals a user can do
	AccountRenewalCountMax uint32 `protobuf:"varint,10,opt,name=AccountRenewalCountMax,proto3" json:"account_renewal_count_max"`
	// DomainGracePeriod defines the grace period for a domain deletion in seconds
	AccountGracePeriod types.Duration `protobuf:"bytes,11,opt,name=AccountGracePeriod,proto3" json:"account_grace_period"`
	// ResourcesMax defines maximum number of resources could be saved under an account
	ResourcesMax uint32 `protobuf:"varint,12,opt,name=ResourcesMax,proto3" json:"resources_max"`
	// CertificateSizeMax defines maximum size of a certificate that could be saved under an account
	CertificateSizeMax uint64 `protobuf:"varint,13,opt,name=CertificateSizeMax,proto3" json:"certificate_size_max"`
	// CertificateCountMax defines maximum number of certificates that could be saved under an account
	CertificateCountMax uint32 `protobuf:"varint,14,opt,name=CertificateCountMax,proto3" json:"certificate_count_max"`
	// MetadataSizeMax defines maximum size of metadata that could be saved under an account
	MetadataSizeMax      uint64   `protobuf:"varint,15,opt,name=MetadataSizeMax,proto3" json:"metadata_size_max"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_c149be06521486db, []int{0}
}
func (m *Config) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Config.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return m.Size()
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetConfigurer() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Configurer
	}
	return nil
}

func (m *Config) GetValidDomainName() string {
	if m != nil {
		return m.ValidDomainName
	}
	return ""
}

func (m *Config) GetValidAccountName() string {
	if m != nil {
		return m.ValidAccountName
	}
	return ""
}

func (m *Config) GetValidURI() string {
	if m != nil {
		return m.ValidURI
	}
	return ""
}

func (m *Config) GetValidResource() string {
	if m != nil {
		return m.ValidResource
	}
	return ""
}

func (m *Config) GetDomainRenewalPeriod() types.Duration {
	if m != nil {
		return m.DomainRenewalPeriod
	}
	return types.Duration{}
}

func (m *Config) GetDomainRenewalCountMax() uint32 {
	if m != nil {
		return m.DomainRenewalCountMax
	}
	return 0
}

func (m *Config) GetDomainGracePeriod() types.Duration {
	if m != nil {
		return m.DomainGracePeriod
	}
	return types.Duration{}
}

func (m *Config) GetAccountRenewalPeriod() types.Duration {
	if m != nil {
		return m.AccountRenewalPeriod
	}
	return types.Duration{}
}

func (m *Config) GetAccountRenewalCountMax() uint32 {
	if m != nil {
		return m.AccountRenewalCountMax
	}
	return 0
}

func (m *Config) GetAccountGracePeriod() types.Duration {
	if m != nil {
		return m.AccountGracePeriod
	}
	return types.Duration{}
}

func (m *Config) GetResourcesMax() uint32 {
	if m != nil {
		return m.ResourcesMax
	}
	return 0
}

func (m *Config) GetCertificateSizeMax() uint64 {
	if m != nil {
		return m.CertificateSizeMax
	}
	return 0
}

func (m *Config) GetCertificateCountMax() uint32 {
	if m != nil {
		return m.CertificateCountMax
	}
	return 0
}

func (m *Config) GetMetadataSizeMax() uint64 {
	if m != nil {
		return m.MetadataSizeMax
	}
	return 0
}

// Fees contains different type of fees
// to calculate coins to detract when
// processing different messages
type Fees struct {
	// FeeCoinDenom defines the denominator of the coin used to process fees
	FeeCoinDenom string `protobuf:"bytes,1,opt,name=FeeCoinDenom,proto3" json:"fee_coin_denom"`
	// FeeCoinPrice defines the price of the coin
	FeeCoinPrice *types1.DecProto `protobuf:"bytes,2,opt,name=FeeCoinPrice,proto3" json:"fee_coin_price"`
	// FeeDefault is the parameter defining the default fee
	FeeDefault *types1.DecProto `protobuf:"bytes,3,opt,name=FeeDefault,proto3" json:"fee_default"`
	// RegisterAccountClosed is the fee to be paid to register an account in a closed domain
	RegisterAccountClosed *types1.DecProto `protobuf:"bytes,4,opt,name=RegisterAccountClosed,proto3" json:"register_account_closed"`
	// RegisterAccountOpen is the fee to be paid to register an account in an open domain
	RegisterAccountOpen *types1.DecProto `protobuf:"bytes,5,opt,name=RegisterAccountOpen,proto3" json:"register_account_open"`
	// TransferAccountClosed is the fee to be paid to register an account in a closed domain
	TransferAccountClosed *types1.DecProto `protobuf:"bytes,6,opt,name=TransferAccountClosed,proto3" json:"transfer_account_closed"`
	// TransferAccountOpen is the fee to be paid to register an account in an open domain
	TransferAccountOpen *types1.DecProto `protobuf:"bytes,7,opt,name=TransferAccountOpen,proto3" json:"transfer_account_open"`
	// ReplaceAccountResources is the fee to be paid to replace account's resources
	ReplaceAccountResources *types1.DecProto `protobuf:"bytes,8,opt,name=ReplaceAccountResources,proto3" json:"replace_account_resources"`
	// AddAccountCertificate is the fee to be paid to add a certificate to an account
	AddAccountCertificate *types1.DecProto `protobuf:"bytes,9,opt,name=AddAccountCertificate,proto3" json:"add_account_certificate"`
	// DelAccountCertificate is the feed to be paid to delete a certificate in an account
	DelAccountCertificate *types1.DecProto `protobuf:"bytes,10,opt,name=DelAccountCertificate,proto3" json:"del_account_certificate"`
	// SetAccountMetadata is the fee to be paid to set account's metadata
	SetAccountMetadata *types1.DecProto `protobuf:"bytes,11,opt,name=SetAccountMetadata,proto3" json:"set_account_metadata"`
	// RegisterDomain1 is the fee to be paid to register a domain with one character
	RegisterDomain1 *types1.DecProto `protobuf:"bytes,12,opt,name=RegisterDomain1,proto3" json:"register_domain_1"`
	// RegisterDomain2 is the fee to be paid to register a domain with two characters
	RegisterDomain2 *types1.DecProto `protobuf:"bytes,13,opt,name=RegisterDomain2,proto3" json:"register_domain_2"`
	// RegisterDomain3 is the fee to be paid to register a domain with three characters
	RegisterDomain3 *types1.DecProto `protobuf:"bytes,14,opt,name=RegisterDomain3,proto3" json:"register_domain_3"`
	// RegisterDomain4 is the fee to be paid to register a domain with four characters
	RegisterDomain4 *types1.DecProto `protobuf:"bytes,15,opt,name=RegisterDomain4,proto3" json:"register_domain_4"`
	// RegisterDomain5 is the fee to be paid to register a domain with five characters
	RegisterDomain5 *types1.DecProto `protobuf:"bytes,16,opt,name=RegisterDomain5,proto3" json:"register_domain_5"`
	// RegisterDomainDefault is the fee to be paid to register a domain with more than five characters
	RegisterDomainDefault *types1.DecProto `protobuf:"bytes,17,opt,name=RegisterDomainDefault,proto3" json:"register_domain_default"`
	// RegisterDomainMultiplier is the multiplication applied to fees in register domain operations if they're of open type
	RegisterOpenDomainMultiplier *types1.DecProto `protobuf:"bytes,18,opt,name=RegisterOpenDomainMultiplier,proto3" json:"register_open_domain_multiplier"`
	// TransferDomainClosed is the fee to be paid to transfer a closed domain
	TransferDomainClosed *types1.DecProto `protobuf:"bytes,19,opt,name=TransferDomainClosed,proto3" json:"transfer_domain_closed"`
	// TransferDomainOpen is the fee to be paid to transfer open domains
	TransferDomainOpen *types1.DecProto `protobuf:"bytes,20,opt,name=TransferDomainOpen,proto3" json:"transfer_domain_open"`
	// RenewDomainOpen is the fee to be paid to renew an open domain
	RenewDomainOpen      github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,21,opt,name=RenewDomainOpen,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"renew_domain_open"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *Fees) Reset()         { *m = Fees{} }
func (m *Fees) String() string { return proto.CompactTextString(m) }
func (*Fees) ProtoMessage()    {}
func (*Fees) Descriptor() ([]byte, []int) {
	return fileDescriptor_c149be06521486db, []int{1}
}
func (m *Fees) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Fees) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Fees.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Fees) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fees.Merge(m, src)
}
func (m *Fees) XXX_Size() int {
	return m.Size()
}
func (m *Fees) XXX_DiscardUnknown() {
	xxx_messageInfo_Fees.DiscardUnknown(m)
}

var xxx_messageInfo_Fees proto.InternalMessageInfo

func (m *Fees) GetFeeCoinDenom() string {
	if m != nil {
		return m.FeeCoinDenom
	}
	return ""
}

func (m *Fees) GetFeeCoinPrice() *types1.DecProto {
	if m != nil {
		return m.FeeCoinPrice
	}
	return nil
}

func (m *Fees) GetFeeDefault() *types1.DecProto {
	if m != nil {
		return m.FeeDefault
	}
	return nil
}

func (m *Fees) GetRegisterAccountClosed() *types1.DecProto {
	if m != nil {
		return m.RegisterAccountClosed
	}
	return nil
}

func (m *Fees) GetRegisterAccountOpen() *types1.DecProto {
	if m != nil {
		return m.RegisterAccountOpen
	}
	return nil
}

func (m *Fees) GetTransferAccountClosed() *types1.DecProto {
	if m != nil {
		return m.TransferAccountClosed
	}
	return nil
}

func (m *Fees) GetTransferAccountOpen() *types1.DecProto {
	if m != nil {
		return m.TransferAccountOpen
	}
	return nil
}

func (m *Fees) GetReplaceAccountResources() *types1.DecProto {
	if m != nil {
		return m.ReplaceAccountResources
	}
	return nil
}

func (m *Fees) GetAddAccountCertificate() *types1.DecProto {
	if m != nil {
		return m.AddAccountCertificate
	}
	return nil
}

func (m *Fees) GetDelAccountCertificate() *types1.DecProto {
	if m != nil {
		return m.DelAccountCertificate
	}
	return nil
}

func (m *Fees) GetSetAccountMetadata() *types1.DecProto {
	if m != nil {
		return m.SetAccountMetadata
	}
	return nil
}

func (m *Fees) GetRegisterDomain1() *types1.DecProto {
	if m != nil {
		return m.RegisterDomain1
	}
	return nil
}

func (m *Fees) GetRegisterDomain2() *types1.DecProto {
	if m != nil {
		return m.RegisterDomain2
	}
	return nil
}

func (m *Fees) GetRegisterDomain3() *types1.DecProto {
	if m != nil {
		return m.RegisterDomain3
	}
	return nil
}

func (m *Fees) GetRegisterDomain4() *types1.DecProto {
	if m != nil {
		return m.RegisterDomain4
	}
	return nil
}

func (m *Fees) GetRegisterDomain5() *types1.DecProto {
	if m != nil {
		return m.RegisterDomain5
	}
	return nil
}

func (m *Fees) GetRegisterDomainDefault() *types1.DecProto {
	if m != nil {
		return m.RegisterDomainDefault
	}
	return nil
}

func (m *Fees) GetRegisterOpenDomainMultiplier() *types1.DecProto {
	if m != nil {
		return m.RegisterOpenDomainMultiplier
	}
	return nil
}

func (m *Fees) GetTransferDomainClosed() *types1.DecProto {
	if m != nil {
		return m.TransferDomainClosed
	}
	return nil
}

func (m *Fees) GetTransferDomainOpen() *types1.DecProto {
	if m != nil {
		return m.TransferDomainOpen
	}
	return nil
}

func init() {
	proto.RegisterType((*Config)(nil), "Config")
	proto.RegisterType((*Fees)(nil), "Fees")
}

func init() { proto.RegisterFile("x/configuration/types/types.proto", fileDescriptor_c149be06521486db) }

var fileDescriptor_c149be06521486db = []byte{
	// 1117 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x97, 0xcd, 0x72, 0xe3, 0x44,
	0x17, 0x86, 0x47, 0xdf, 0x17, 0x32, 0x93, 0x4e, 0x32, 0x99, 0x74, 0x7e, 0x46, 0x99, 0x49, 0x2c,
	0x33, 0x54, 0x51, 0x66, 0x11, 0xa9, 0xe2, 0x24, 0x14, 0xbb, 0x21, 0xb6, 0x2b, 0x40, 0x51, 0x19,
	0x52, 0x3d, 0x84, 0x05, 0x0b, 0x5c, 0x6d, 0xe9, 0xd8, 0x08, 0x24, 0xb5, 0x4b, 0x92, 0x93, 0x30,
	0x17, 0x40, 0x71, 0x09, 0xdc, 0x09, 0xb7, 0x30, 0x4b, 0xd6, 0x2c, 0x54, 0x54, 0xd8, 0xe9, 0x12,
	0x58, 0x51, 0xfd, 0x23, 0x59, 0x92, 0x35, 0xd8, 0x64, 0x13, 0x3b, 0x7d, 0xfa, 0x3c, 0xef, 0xe9,
	0xd3, 0xdd, 0xaf, 0x64, 0xf4, 0xfe, 0xad, 0x65, 0xb3, 0x60, 0xe8, 0x8e, 0x26, 0x21, 0x8d, 0x5d,
	0x16, 0x58, 0xf1, 0x4f, 0x63, 0x88, 0xe4, 0x5f, 0x73, 0x1c, 0xb2, 0x98, 0x3d, 0xdb, 0x1e, 0xb1,
	0x11, 0x13, 0x5f, 0x2d, 0xfe, 0x4d, 0x8d, 0x36, 0x46, 0x8c, 0x8d, 0x3c, 0xb0, 0xc4, 0x7f, 0x83,
	0xc9, 0xd0, 0x72, 0x14, 0x21, 0x8b, 0xdb, 0x2c, 0xf2, 0x59, 0x64, 0x0d, 0x68, 0x04, 0xd6, 0xf5,
	0xd1, 0x00, 0x62, 0x7a, 0x64, 0xd9, 0xcc, 0x55, 0xf1, 0x17, 0xbf, 0xad, 0xa0, 0xe5, 0xae, 0x50,
	0xc6, 0x7d, 0x84, 0xba, 0xaa, 0x06, 0x08, 0x75, 0xad, 0xa9, 0xb5, 0xd6, 0x3a, 0x2f, 0xd3, 0xc4,
	0x40, 0x76, 0x3e, 0xfa, 0x77, 0x62, 0x1c, 0x8e, 0xdc, 0xf8, 0xfb, 0xc9, 0xc0, 0xb4, 0x99, 0x6f,
	0x29, 0xb6, 0xfc, 0x38, 0x8c, 0x9c, 0x1f, 0x55, 0xc1, 0x67, 0xb6, 0x7d, 0xe6, 0x38, 0x21, 0x44,
	0x11, 0x29, 0x20, 0xf1, 0x4b, 0xb4, 0xf1, 0x0d, 0xf5, 0x5c, 0xa7, 0xc7, 0x7c, 0xea, 0x06, 0xaf,
	0xa8, 0x0f, 0xfa, 0xff, 0x9a, 0x5a, 0x6b, 0xa5, 0xb3, 0x93, 0x26, 0xc6, 0xe6, 0x35, 0x0f, 0xf5,
	0x1d, 0x11, 0xeb, 0x07, 0xd4, 0x07, 0x52, 0x9d, 0x8d, 0x3b, 0xe8, 0x89, 0x18, 0x3a, 0xb3, 0x6d,
	0x36, 0x09, 0x62, 0x41, 0xf8, 0xbf, 0x20, 0xec, 0xa6, 0x89, 0x81, 0x25, 0x81, 0xca, 0xa0, 0x44,
	0xcc, 0xcc, 0xc7, 0x1f, 0xa1, 0x47, 0x62, 0xec, 0x8a, 0x7c, 0xa1, 0x2f, 0x89, 0xdc, 0xf5, 0x34,
	0x31, 0x56, 0x64, 0xee, 0x24, 0x74, 0x49, 0x1e, 0xc6, 0x9f, 0xa0, 0x75, 0xf1, 0x9d, 0x40, 0xc4,
	0x26, 0xa1, 0x0d, 0xfa, 0x7b, 0x62, 0x3e, 0x4e, 0x13, 0xe3, 0xb1, 0x9c, 0x1f, 0xaa, 0x08, 0x29,
	0x4f, 0xc4, 0x3f, 0xa0, 0x2d, 0x59, 0x36, 0x81, 0x00, 0x6e, 0xa8, 0x77, 0x09, 0xa1, 0xcb, 0x1c,
	0x7d, 0xb9, 0xa9, 0xb5, 0x56, 0xdb, 0x7b, 0xa6, 0xdc, 0x33, 0x33, 0xdb, 0x33, 0xb3, 0xa7, 0xf6,
	0xac, 0x73, 0xf0, 0x36, 0x31, 0x1e, 0xa4, 0x89, 0xb1, 0xa3, 0xda, 0x10, 0xca, 0xf4, 0xfe, 0x58,
	0xe4, 0x93, 0x3a, 0x28, 0x26, 0x68, 0xa7, 0x34, 0xdc, 0xe5, 0x4b, 0xbd, 0xa0, 0xb7, 0xfa, 0xc3,
	0xa6, 0xd6, 0x5a, 0xef, 0xec, 0xa7, 0x89, 0xa1, 0x57, 0x70, 0xb2, 0x41, 0x3e, 0xbd, 0x25, 0xf5,
	0xa9, 0xd8, 0x41, 0x9b, 0x32, 0xf0, 0x59, 0x48, 0x6d, 0x50, 0xd5, 0x3f, 0x9a, 0x57, 0xfd, 0x73,
	0x55, 0xfd, 0x96, 0x92, 0x1b, 0xf1, 0xe4, 0xac, 0xf6, 0x59, 0x20, 0xf6, 0xd1, 0xb6, 0xda, 0x99,
	0x72, 0x9b, 0x56, 0xe6, 0x09, 0x35, 0x94, 0xd0, 0x6e, 0xb6, 0xd7, 0x95, 0x3e, 0xd5, 0x62, 0xf1,
	0x15, 0xda, 0x2d, 0x8f, 0xe7, 0x9d, 0x42, 0xa2, 0x53, 0x07, 0x69, 0x62, 0xec, 0x55, 0x89, 0xd3,
	0x56, 0xbd, 0x23, 0x19, 0x8f, 0x10, 0x56, 0x91, 0x62, 0xb3, 0x56, 0xe7, 0xad, 0x61, 0x5f, 0xad,
	0x61, 0x3b, 0x53, 0x2c, 0x75, 0xab, 0x06, 0x89, 0x4f, 0xd1, 0x5a, 0x76, 0xc0, 0x22, 0x5e, 0xf5,
	0x9a, 0xa8, 0x7a, 0x33, 0x4d, 0x8c, 0xf5, 0xec, 0x1c, 0x46, 0xa2, 0xd2, 0xd2, 0x34, 0xfc, 0x39,
	0xc2, 0x5d, 0x08, 0x63, 0x77, 0xe8, 0xda, 0x34, 0x86, 0xd7, 0xee, 0x1b, 0xe0, 0xc9, 0xeb, 0x4d,
	0xad, 0xb5, 0xd4, 0xd1, 0x79, 0x01, 0xf6, 0x34, 0xda, 0x8f, 0xdc, 0x37, 0x20, 0x18, 0x35, 0x39,
	0xf8, 0x4b, 0xb4, 0x55, 0x18, 0xcd, 0xbb, 0xf7, 0x58, 0xd4, 0xb1, 0xc7, 0x8f, 0x6d, 0x11, 0x35,
	0xed, 0x5c, 0x5d, 0x16, 0x37, 0x83, 0x0b, 0x88, 0xa9, 0x43, 0x63, 0x9a, 0xd5, 0xb4, 0x21, 0x6a,
	0x12, 0x66, 0xe0, 0xab, 0xd0, 0xb4, 0xa0, 0xea, 0xec, 0x17, 0xbf, 0x6c, 0xa2, 0xa5, 0x73, 0x80,
	0x08, 0x7f, 0x8c, 0xd6, 0xce, 0x01, 0xba, 0xcc, 0x0d, 0x7a, 0x10, 0x30, 0x5f, 0x38, 0x97, 0xba,
	0xa5, 0x43, 0xe0, 0x75, 0xb8, 0x41, 0xdf, 0xe1, 0x11, 0x52, 0x9a, 0x87, 0xaf, 0xf2, 0xbc, 0xcb,
	0xd0, 0xb5, 0xa5, 0x17, 0xad, 0xb6, 0x0f, 0x4c, 0x69, 0x67, 0x26, 0x77, 0x4c, 0x53, 0x39, 0xa6,
	0xd9, 0x03, 0xfb, 0x92, 0x6f, 0x61, 0x05, 0x3b, 0xe6, 0x89, 0xa4, 0x84, 0xc1, 0xaf, 0x10, 0x3a,
	0x07, 0xe8, 0xc1, 0x90, 0x4e, 0xbc, 0x58, 0xd8, 0xd3, 0x5c, 0xe8, 0x46, 0x9a, 0x18, 0xab, 0x1c,
	0xea, 0xc8, 0x2c, 0x52, 0x20, 0xe0, 0x31, 0xda, 0x21, 0x30, 0x72, 0xa3, 0x18, 0x42, 0x75, 0x28,
	0xba, 0x1e, 0x8b, 0xc0, 0x11, 0xee, 0x35, 0x17, 0xfd, 0x3c, 0x4d, 0x8c, 0xa7, 0xa1, 0xca, 0xcf,
	0xbd, 0xd1, 0x16, 0x04, 0x52, 0x0f, 0xe6, 0xee, 0x55, 0x09, 0x7c, 0x35, 0x86, 0x40, 0xb8, 0xdf,
	0x5c, 0x3d, 0x71, 0x0c, 0x66, 0xf4, 0xd8, 0x18, 0x02, 0x52, 0x07, 0xe5, 0xab, 0xfb, 0x3a, 0xa4,
	0x41, 0x34, 0xac, 0xae, 0x6e, 0x79, 0xe1, 0xd5, 0xc5, 0x2a, 0x7f, 0x66, 0x75, 0xb5, 0x60, 0xbe,
	0xba, 0x4a, 0x40, 0xac, 0xee, 0xe1, 0xc2, 0xab, 0x9b, 0xd1, 0x93, 0xab, 0xab, 0x81, 0xe2, 0x6b,
	0xf4, 0x94, 0xc0, 0xd8, 0xa3, 0x36, 0xe4, 0xe6, 0xa1, 0x6e, 0xa6, 0x72, 0xd3, 0x39, 0x7a, 0xc2,
	0x92, 0x42, 0x49, 0xe8, 0x4f, 0xad, 0x49, 0x31, 0xc8, 0xbb, 0xe0, 0xbc, 0xab, 0x67, 0x4e, 0xf6,
	0xd8, 0x2b, 0xdc, 0x3e, 0x65, 0xad, 0x8b, 0x74, 0x95, 0x3a, 0xd3, 0x47, 0x69, 0xe1, 0x5a, 0x93,
	0x7a, 0x30, 0x57, 0xec, 0x81, 0x57, 0xa3, 0x88, 0x16, 0x56, 0x74, 0xc0, 0xab, 0x57, 0xac, 0x05,
	0x73, 0xdf, 0x7d, 0x0d, 0xb1, 0x0a, 0x64, 0xe6, 0xa0, 0x7c, 0x77, 0x8e, 0x9c, 0xb0, 0xbd, 0x08,
	0xe2, 0x5c, 0x2e, 0xb3, 0x1b, 0x52, 0x83, 0xc4, 0xdf, 0xa1, 0x8d, 0xec, 0xe4, 0xca, 0x67, 0xd8,
	0x91, 0xb0, 0xde, 0xb9, 0x2a, 0xc2, 0xc8, 0xf2, 0xab, 0xa0, 0x9e, 0x89, 0x47, 0xa4, 0x0a, 0x9b,
	0xe5, 0xb7, 0x85, 0x3b, 0xdf, 0x8f, 0xdf, 0xae, 0xf2, 0xdb, 0xb3, 0xfc, 0x63, 0x61, 0xd9, 0xf7,
	0xe3, 0x1f, 0x57, 0xf9, 0xc7, 0xb3, 0xfc, 0x13, 0xe1, 0xe4, 0xf7, 0xe3, 0x9f, 0x54, 0xf9, 0x27,
	0xb3, 0xfc, 0x53, 0xfd, 0xc9, 0xbd, 0xf9, 0xa7, 0x55, 0xfe, 0x69, 0xd1, 0x60, 0xe5, 0x50, 0xe6,
	0xdd, 0x9b, 0xff, 0xdd, 0x60, 0x95, 0x4a, 0xe6, 0xe3, 0xf5, 0x60, 0xfc, 0xb3, 0x86, 0xf6, 0xb3,
	0x08, 0xf7, 0x09, 0x19, 0xbd, 0x98, 0x78, 0xb1, 0x3b, 0xf6, 0x5c, 0x08, 0x75, 0xbc, 0x88, 0xf2,
	0x07, 0x69, 0x62, 0x18, 0xb9, 0x32, 0x37, 0xa1, 0x4c, 0xde, 0xcf, 0x49, 0xe4, 0x5f, 0x75, 0xf8,
	0x1b, 0x58, 0x66, 0x5b, 0x32, 0xa6, 0xcc, 0x77, 0x6b, 0x11, 0xfd, 0x67, 0xfc, 0x0d, 0x2c, 0x37,
	0x43, 0x25, 0xad, 0xbc, 0xb7, 0x16, 0xcb, 0xaf, 0x6c, 0x79, 0x5c, 0x38, 0xef, 0xf6, 0xc2, 0x57,
	0xb6, 0x2a, 0x26, 0x8c, 0xb7, 0x06, 0x89, 0x7d, 0x7e, 0x64, 0x02, 0xb8, 0x29, 0xa8, 0xec, 0x88,
	0xb7, 0x82, 0x2e, 0x7f, 0xeb, 0xfa, 0x23, 0x31, 0x3e, 0x5c, 0xe0, 0x57, 0x4c, 0x0f, 0x6c, 0x79,
	0x82, 0x02, 0xb8, 0x29, 0x29, 0x56, 0xd9, 0x9d, 0x4f, 0xdf, 0xde, 0x35, 0xb4, 0xdf, 0xef, 0x1a,
	0xda, 0x9f, 0x77, 0x0d, 0xed, 0xd7, 0xbf, 0x1a, 0x0f, 0xbe, 0x35, 0x0b, 0x7c, 0x97, 0x5d, 0x1f,
	0xb2, 0x00, 0xf8, 0x67, 0x10, 0x59, 0xb5, 0x3f, 0xf4, 0x06, 0xcb, 0xe2, 0x05, 0xf1, 0xf8, 0x9f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x23, 0x81, 0xf7, 0x42, 0x08, 0x0e, 0x00, 0x00,
}

func (m *Config) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Config) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Config) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.MetadataSizeMax != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.MetadataSizeMax))
		i--
		dAtA[i] = 0x78
	}
	if m.CertificateCountMax != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.CertificateCountMax))
		i--
		dAtA[i] = 0x70
	}
	if m.CertificateSizeMax != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.CertificateSizeMax))
		i--
		dAtA[i] = 0x68
	}
	if m.ResourcesMax != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ResourcesMax))
		i--
		dAtA[i] = 0x60
	}
	{
		size, err := m.AccountGracePeriod.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x5a
	if m.AccountRenewalCountMax != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.AccountRenewalCountMax))
		i--
		dAtA[i] = 0x50
	}
	{
		size, err := m.AccountRenewalPeriod.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	{
		size, err := m.DomainGracePeriod.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	if m.DomainRenewalCountMax != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.DomainRenewalCountMax))
		i--
		dAtA[i] = 0x38
	}
	{
		size, err := m.DomainRenewalPeriod.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if len(m.ValidResource) > 0 {
		i -= len(m.ValidResource)
		copy(dAtA[i:], m.ValidResource)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ValidResource)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ValidURI) > 0 {
		i -= len(m.ValidURI)
		copy(dAtA[i:], m.ValidURI)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ValidURI)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ValidAccountName) > 0 {
		i -= len(m.ValidAccountName)
		copy(dAtA[i:], m.ValidAccountName)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ValidAccountName)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ValidDomainName) > 0 {
		i -= len(m.ValidDomainName)
		copy(dAtA[i:], m.ValidDomainName)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ValidDomainName)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Configurer) > 0 {
		i -= len(m.Configurer)
		copy(dAtA[i:], m.Configurer)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Configurer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Fees) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Fees) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Fees) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.RenewDomainOpen) > 0 {
		i -= len(m.RenewDomainOpen)
		copy(dAtA[i:], m.RenewDomainOpen)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.RenewDomainOpen)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xaa
	}
	if m.TransferDomainOpen != nil {
		{
			size, err := m.TransferDomainOpen.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa2
	}
	if m.TransferDomainClosed != nil {
		{
			size, err := m.TransferDomainClosed.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x9a
	}
	if m.RegisterOpenDomainMultiplier != nil {
		{
			size, err := m.RegisterOpenDomainMultiplier.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x92
	}
	if m.RegisterDomainDefault != nil {
		{
			size, err := m.RegisterDomainDefault.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x8a
	}
	if m.RegisterDomain5 != nil {
		{
			size, err := m.RegisterDomain5.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x82
	}
	if m.RegisterDomain4 != nil {
		{
			size, err := m.RegisterDomain4.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x7a
	}
	if m.RegisterDomain3 != nil {
		{
			size, err := m.RegisterDomain3.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x72
	}
	if m.RegisterDomain2 != nil {
		{
			size, err := m.RegisterDomain2.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x6a
	}
	if m.RegisterDomain1 != nil {
		{
			size, err := m.RegisterDomain1.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x62
	}
	if m.SetAccountMetadata != nil {
		{
			size, err := m.SetAccountMetadata.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x5a
	}
	if m.DelAccountCertificate != nil {
		{
			size, err := m.DelAccountCertificate.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x52
	}
	if m.AddAccountCertificate != nil {
		{
			size, err := m.AddAccountCertificate.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x4a
	}
	if m.ReplaceAccountResources != nil {
		{
			size, err := m.ReplaceAccountResources.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x42
	}
	if m.TransferAccountOpen != nil {
		{
			size, err := m.TransferAccountOpen.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	if m.TransferAccountClosed != nil {
		{
			size, err := m.TransferAccountClosed.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if m.RegisterAccountOpen != nil {
		{
			size, err := m.RegisterAccountOpen.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.RegisterAccountClosed != nil {
		{
			size, err := m.RegisterAccountClosed.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.FeeDefault != nil {
		{
			size, err := m.FeeDefault.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.FeeCoinPrice != nil {
		{
			size, err := m.FeeCoinPrice.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.FeeCoinDenom) > 0 {
		i -= len(m.FeeCoinDenom)
		copy(dAtA[i:], m.FeeCoinDenom)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.FeeCoinDenom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Config) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Configurer)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.ValidDomainName)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.ValidAccountName)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.ValidURI)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.ValidResource)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = m.DomainRenewalPeriod.Size()
	n += 1 + l + sovTypes(uint64(l))
	if m.DomainRenewalCountMax != 0 {
		n += 1 + sovTypes(uint64(m.DomainRenewalCountMax))
	}
	l = m.DomainGracePeriod.Size()
	n += 1 + l + sovTypes(uint64(l))
	l = m.AccountRenewalPeriod.Size()
	n += 1 + l + sovTypes(uint64(l))
	if m.AccountRenewalCountMax != 0 {
		n += 1 + sovTypes(uint64(m.AccountRenewalCountMax))
	}
	l = m.AccountGracePeriod.Size()
	n += 1 + l + sovTypes(uint64(l))
	if m.ResourcesMax != 0 {
		n += 1 + sovTypes(uint64(m.ResourcesMax))
	}
	if m.CertificateSizeMax != 0 {
		n += 1 + sovTypes(uint64(m.CertificateSizeMax))
	}
	if m.CertificateCountMax != 0 {
		n += 1 + sovTypes(uint64(m.CertificateCountMax))
	}
	if m.MetadataSizeMax != 0 {
		n += 1 + sovTypes(uint64(m.MetadataSizeMax))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Fees) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FeeCoinDenom)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.FeeCoinPrice != nil {
		l = m.FeeCoinPrice.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.FeeDefault != nil {
		l = m.FeeDefault.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.RegisterAccountClosed != nil {
		l = m.RegisterAccountClosed.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.RegisterAccountOpen != nil {
		l = m.RegisterAccountOpen.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.TransferAccountClosed != nil {
		l = m.TransferAccountClosed.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.TransferAccountOpen != nil {
		l = m.TransferAccountOpen.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.ReplaceAccountResources != nil {
		l = m.ReplaceAccountResources.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.AddAccountCertificate != nil {
		l = m.AddAccountCertificate.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.DelAccountCertificate != nil {
		l = m.DelAccountCertificate.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.SetAccountMetadata != nil {
		l = m.SetAccountMetadata.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.RegisterDomain1 != nil {
		l = m.RegisterDomain1.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.RegisterDomain2 != nil {
		l = m.RegisterDomain2.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.RegisterDomain3 != nil {
		l = m.RegisterDomain3.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.RegisterDomain4 != nil {
		l = m.RegisterDomain4.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.RegisterDomain5 != nil {
		l = m.RegisterDomain5.Size()
		n += 2 + l + sovTypes(uint64(l))
	}
	if m.RegisterDomainDefault != nil {
		l = m.RegisterDomainDefault.Size()
		n += 2 + l + sovTypes(uint64(l))
	}
	if m.RegisterOpenDomainMultiplier != nil {
		l = m.RegisterOpenDomainMultiplier.Size()
		n += 2 + l + sovTypes(uint64(l))
	}
	if m.TransferDomainClosed != nil {
		l = m.TransferDomainClosed.Size()
		n += 2 + l + sovTypes(uint64(l))
	}
	if m.TransferDomainOpen != nil {
		l = m.TransferDomainOpen.Size()
		n += 2 + l + sovTypes(uint64(l))
	}
	l = len(m.RenewDomainOpen)
	if l > 0 {
		n += 2 + l + sovTypes(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Config) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Config: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Config: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Configurer", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Configurer = append(m.Configurer[:0], dAtA[iNdEx:postIndex]...)
			if m.Configurer == nil {
				m.Configurer = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidDomainName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidDomainName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidAccountName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidAccountName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidURI", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidURI = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidResource", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidResource = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DomainRenewalPeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DomainRenewalPeriod.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DomainRenewalCountMax", wireType)
			}
			m.DomainRenewalCountMax = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DomainRenewalCountMax |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DomainGracePeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DomainGracePeriod.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountRenewalPeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AccountRenewalPeriod.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountRenewalCountMax", wireType)
			}
			m.AccountRenewalCountMax = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AccountRenewalCountMax |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountGracePeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AccountGracePeriod.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResourcesMax", wireType)
			}
			m.ResourcesMax = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ResourcesMax |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CertificateSizeMax", wireType)
			}
			m.CertificateSizeMax = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CertificateSizeMax |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CertificateCountMax", wireType)
			}
			m.CertificateCountMax = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CertificateCountMax |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetadataSizeMax", wireType)
			}
			m.MetadataSizeMax = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MetadataSizeMax |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Fees) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Fees: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Fees: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeCoinDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeeCoinDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeCoinPrice", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.FeeCoinPrice == nil {
				m.FeeCoinPrice = &types1.DecProto{}
			}
			if err := m.FeeCoinPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeDefault", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.FeeDefault == nil {
				m.FeeDefault = &types1.DecProto{}
			}
			if err := m.FeeDefault.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegisterAccountClosed", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RegisterAccountClosed == nil {
				m.RegisterAccountClosed = &types1.DecProto{}
			}
			if err := m.RegisterAccountClosed.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegisterAccountOpen", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RegisterAccountOpen == nil {
				m.RegisterAccountOpen = &types1.DecProto{}
			}
			if err := m.RegisterAccountOpen.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransferAccountClosed", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TransferAccountClosed == nil {
				m.TransferAccountClosed = &types1.DecProto{}
			}
			if err := m.TransferAccountClosed.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransferAccountOpen", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TransferAccountOpen == nil {
				m.TransferAccountOpen = &types1.DecProto{}
			}
			if err := m.TransferAccountOpen.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReplaceAccountResources", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ReplaceAccountResources == nil {
				m.ReplaceAccountResources = &types1.DecProto{}
			}
			if err := m.ReplaceAccountResources.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddAccountCertificate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AddAccountCertificate == nil {
				m.AddAccountCertificate = &types1.DecProto{}
			}
			if err := m.AddAccountCertificate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelAccountCertificate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DelAccountCertificate == nil {
				m.DelAccountCertificate = &types1.DecProto{}
			}
			if err := m.DelAccountCertificate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SetAccountMetadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SetAccountMetadata == nil {
				m.SetAccountMetadata = &types1.DecProto{}
			}
			if err := m.SetAccountMetadata.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegisterDomain1", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RegisterDomain1 == nil {
				m.RegisterDomain1 = &types1.DecProto{}
			}
			if err := m.RegisterDomain1.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegisterDomain2", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RegisterDomain2 == nil {
				m.RegisterDomain2 = &types1.DecProto{}
			}
			if err := m.RegisterDomain2.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegisterDomain3", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RegisterDomain3 == nil {
				m.RegisterDomain3 = &types1.DecProto{}
			}
			if err := m.RegisterDomain3.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegisterDomain4", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RegisterDomain4 == nil {
				m.RegisterDomain4 = &types1.DecProto{}
			}
			if err := m.RegisterDomain4.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegisterDomain5", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RegisterDomain5 == nil {
				m.RegisterDomain5 = &types1.DecProto{}
			}
			if err := m.RegisterDomain5.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegisterDomainDefault", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RegisterDomainDefault == nil {
				m.RegisterDomainDefault = &types1.DecProto{}
			}
			if err := m.RegisterDomainDefault.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegisterOpenDomainMultiplier", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RegisterOpenDomainMultiplier == nil {
				m.RegisterOpenDomainMultiplier = &types1.DecProto{}
			}
			if err := m.RegisterOpenDomainMultiplier.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 19:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransferDomainClosed", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TransferDomainClosed == nil {
				m.TransferDomainClosed = &types1.DecProto{}
			}
			if err := m.TransferDomainClosed.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 20:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransferDomainOpen", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TransferDomainOpen == nil {
				m.TransferDomainOpen = &types1.DecProto{}
			}
			if err := m.TransferDomainOpen.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 21:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RenewDomainOpen", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RenewDomainOpen = github_com_cosmos_cosmos_sdk_types.Dec(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
